spring.application.name=company
server.port=8080

# ??????????? ? MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/email_service?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=app_user
spring.datasource.password=app_password
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# JPA ?????????
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.example.emailservice=DEBUG
logging.level.org.springframework.web=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000

spring.jpa.open-in-view=false

spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml